// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFqWdoz5des6asrHs0guMgurh9M2zbZBA',
    appId: '1:572351569991:web:04f22e25f0863e9de25162',
    messagingSenderId: '572351569991',
    projectId: 'flutterdev-76e33',
    authDomain: 'flutterdev-76e33.firebaseapp.com',
    databaseURL: 'https://flutterdev-76e33-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdev-76e33.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEWh3WTGDU_hxnTWduZnuSwgwM7-eN5O4',
    appId: '1:572351569991:android:8381e864580f8bcce25162',
    messagingSenderId: '572351569991',
    projectId: 'flutterdev-76e33',
    databaseURL: 'https://flutterdev-76e33-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdev-76e33.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3aHmwlopruhyVyjnEvnBA7B-VlixFSQ',
    appId: '1:572351569991:ios:67e65efa4b60e6fbe25162',
    messagingSenderId: '572351569991',
    projectId: 'flutterdev-76e33',
    databaseURL: 'https://flutterdev-76e33-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdev-76e33.appspot.com',
    iosClientId: '572351569991-lmcp6k4h71s1q2ks4sd1f457hc3qqfbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.littleHappyfish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3aHmwlopruhyVyjnEvnBA7B-VlixFSQ',
    appId: '1:572351569991:ios:67e65efa4b60e6fbe25162',
    messagingSenderId: '572351569991',
    projectId: 'flutterdev-76e33',
    databaseURL: 'https://flutterdev-76e33-default-rtdb.firebaseio.com',
    storageBucket: 'flutterdev-76e33.appspot.com',
    iosClientId: '572351569991-lmcp6k4h71s1q2ks4sd1f457hc3qqfbg.apps.googleusercontent.com',
    iosBundleId: 'com.example.littleHappyfish',
  );
}
